name: Code Quality (infra)

on:
  push:
    paths:
      - "infra/**"
  pull_request:
    paths:
      - "infra/**"

jobs:
  quality-checks:
    name: Run formatting and linting checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Check Terraform formatting
        working-directory: infra
        run: terraform fmt -check -recursive

      - name: Validate Terraform configuration
        working-directory: infra
        run: |
          terraform init -backend=false -input=false
          terraform validate
